name: Concall Bot

on:
  schedule:
    - cron: '30 6 * * *'   # 12 PM India
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install yt-dlp

      - name: Run script
        run: |
          python script.py

      - name: Commit transcripts
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Daily transcripts update" || echo "No changes"
          git push
